import { Injectable, Logger } from '@nestjs/common';
import * as fs from 'fs';
import * as path from 'path';
import { CodeParserService, ParsedFile } from './code-parser.service';

export interface WriteResult {
  productId: string;
  moduleName: string;
  outputDir: string;
  filesWritten: string[];
}

@Injectable()
export class WriterService {
  private readonly logger = new Logger(WriterService.name);
  // Output lives in a mounted volume in Docker, or ./output locally
  private readonly outputBase = process.env['OUTPUT_DIR'] || path.join(process.cwd(), 'output');

  constructor(private readonly codeParser: CodeParserService) {}

  async write(productId: string, moduleName: string, code: string): Promise<WriteResult> {
    // Parse the generated code string into individual files
    const parsedFiles: ParsedFile[] = this.codeParser.parse(moduleName, code);

    // Build the output path: output/{productId}/{module-slug}/
    const slug = moduleName.toLowerCase().replace(/\s+module$/, '').replace(/\s+/g, '-');
    const outputDir = path.join(this.outputBase, productId, slug);

    // Create the directory tree if it doesn't exist
    fs.mkdirSync(outputDir, { recursive: true });

    // Write each parsed file to disk
    const filesWritten: string[] = [];
    for (const file of parsedFiles) {
      const filePath = path.join(outputDir, file.filename);
      fs.writeFileSync(filePath, file.content, 'utf8');
      filesWritten.push(filePath);
      this.logger.log(`Written: ${filePath}`);
    }

    // Also write a README for the module so the output is self-documenting
    const readmePath = path.join(outputDir, 'README.md');
    fs.writeFileSync(readmePath, this.generateReadme(moduleName, filesWritten), 'utf8');
    filesWritten.push(readmePath);

    this.logger.log(`Module "${moduleName}" written to ${outputDir} — ${filesWritten.length} files`);
    return { productId, moduleName, outputDir, filesWritten };
  }

  listOutput(productId: string): Record<string, string[]> {
    const productDir = path.join(this.outputBase, productId);
    if (!fs.existsSync(productDir)) return {};

    const result: Record<string, string[]> = {};
    const modules = fs.readdirSync(productDir);
    for (const mod of modules) {
      const modPath = path.join(productDir, mod);
      if (fs.statSync(modPath).isDirectory()) {
        result[mod] = fs.readdirSync(modPath);
      }
    }
    return result;
  }

  private generateReadme(moduleName: string, files: string[]): string {
    const fileList = files.map((f) => `- \`${path.basename(f)}\``).join('\n');
    return `# ${moduleName}\n\nGenerated by AI Application Factory.\n\n## Files\n\n${fileList}\n`;
  }
}
