events {
  worker_connections 1024;
}

http {
  upstream generator_active {
    server generator-agent-blue:3000;
  }
  upstream validation_active {
    server validation-agent-blue:3000;
  }

  server {
    listen 80;

    location /api/jobs {
      proxy_pass http://generator_active;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/validate {
      proxy_pass http://validation_active;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
      return 200 'nginx ok';
      add_header Content-Type text/plain;
    }
  }
}
